name: pulsenow_flutter
description: PulseNow Flutter Assessment - Crypto Trading & Analytics Platform
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.5+1

  # HTTP Client
  dio: ^5.4.0

  # UI
  cupertino_icons: ^1.0.6

  # Utilities
  intl: ^0.18.1
  dartz: ^0.10.1

  # WebSocket
  web_socket_channel: ^3.0.2

  # Skeleton Loading
  skeletonizer: ^2.1.0+1

  # Smart Refresh
  pull_to_refresh: ^2.0.0
  google_nav_bar: ^5.0.7
  fl_chart: ^1.1.1

  equatable: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
